name: covid_flutter
description: A simple app that shows countries covid data

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.1
  json_annotation: ^4.4.0
  cupertino_icons: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  build_runner: ^2.1.7
  json_serializable: ^6.1.3

flutter:
  fonts:
    - family: Regular
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
    - family: Medium
      fonts:
        - asset: fonts/OpenSans-Medium.ttf
    - family: SemiBold
      fonts:
        - asset: fonts/OpenSans-SemiBold.ttf
    - family: Bold
      fonts:
        - asset: fonts/OpenSans-Bold.ttf

  uses-material-design: true
